class LocalNutritionBase {
  late double calories;
  late double fat;
  late double fatSaturated;
  late double fatTrans;
  late double fatPolyunsaturated;
  late double fatMonounsaturated;
  late double cholesterol;
  late double carbohydrates;
  late double fiber;
  late double insolubleFiber;
  late double sugar;
  late double protein;
  late double sodium;
  late double potassium;
  late double calcium;
  late double iron;
  late double vitaminA;
  late double vitaminC;
  late double vitaminD;
}
